spring:
  application:
    name: hotel-server
  zipkin:
    base-url: http://localhost:8020

server:
  port: 8007

mybatis:
  typeAliasesPackage: cn.lyf.hotelserver.entity
  mapperLocations: classpath*:mapper/*.xml

management:
  security:
    enabled: false

feign.hystirx.enable: true

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8002/auth/user
      prefer-token-info: false